---

driver_plugin: vagrant

platforms:
<% %w(11.4.0 10.24.0).each do |chef_version| %>
- name: ubuntu-12.04-<%= chef_version %>
  driver_config:
    box: canonical-ubuntu-12.04
    box_url: http://uec-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box
    require_chef_omnibus: <%= chef_version %>
  run_list:
  - recipe[apt]
- name: ubuntu-10.04-<%= chef_version %>
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-10.04.box
    require_chef_omnibus: <%= chef_version %>
  run_list:
  - recipe[apt]
- name: centos-6.3-<%= chef_version %>
  driver_config:
    box: opscode-centos-6.3
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-centos-6.3.box
    require_chef_omnibus: <%= chef_version %>
  run_list:
  - recipe[yum::epel]
- name: centos-5.8-<%= chef_version %>
  driver_config:
    box: opscode-centos-5.8
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-centos-5.8.box
    require_chef_omnibus: <%= chef_version %>
  run_list:
  - recipe[yum::epel]
<% end %>

suites:
- name: instance
  run_list:
  - recipe[runit::default]
  - recipe[ls_test::instance]
  attributes:
    logstash:
      url: https://logstash.objects.dreamhost.com/release/logstash-1.1.9-monolithic.jar
      checksum: e444e89a90583a75c2d6539e5222e2803621baa0ae94cb77dbbcebacdc0c3fc7
