language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - rbx-19mode
  - ruby-head
gemfile: Gemfile.travis
before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script: bundle exec rake test:minitest
